### ISSUE TITLE
module isn't compatible with RedHat 6.X

### ISSUE THREAD

**Issue by tibers** [locp/cassandra#324]
When I kick a CentOS7 box here, the cassandra.yaml file is generated fine.

When I kicked a RH6.7 box, it is truncatred.

When I kicked a RH6.8 box, it's also truncated.

The cassandra.yaml on the broken RH6.x boxes is as follows:
```
# This file is managed by Puppet.  Manual changes are likely to be
# overwritten.  If you see that the YAML indentation looks somewhat strange,
# don't worry, please see the following ticker for more details.
# https://tickets.puppetlabs.com/browse/PUP-3120
---
hints_directory: "/var/lib/cassandra/hints"
```

When I rekick the box with exactly the same configs as a CentOS7 box, it works. Something seems goofy and I'm not sure what.

**Comment by tibers** [comment]
OHKAY. So after more fiddling about, centos7 works with the old "classic" hiera and RedHat is what's working as designed. I still think it's an issue but this is really... weird...

**Comment by dallinb** [comment]
Can you give me as much of the details as possible listed here https://github.com/locp/cassandra/blob/master/CONTRIBUTING.md#raising-an-issue
and also what version of Ruby is installed with the 6.X versions of CentOS?

**Comment by tibers** [comment]
**The version of the locp-cassandra module that you are using:** 2.1.0
**The version of Cassandra that you are installing:** 3.0.5-1
**The operating system and release (output from facter os would be appropriate):** 
```
os => {
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "RedHat",
  release => {
    full => "6.8",
    major => "6",
    minor => "8"
  },
  selinux => {
    enabled => false
  }
}
os_maj_version => 6
```
**A sample of your manifest/profile that is calling the cassandra module. Feel free to obfuscate sections of the code that contain details that are confidential (e.g. passwords and other secrets).**
This is where I was lazy. I wrote new yaml for the group of boxes I wanted to migrate but left "classic API" yaml in the common.yaml. I think it's probably something in our configuration here, but the result of having centos differ from rhel6 is unexpected. I'm guessing I'm not the first person to get hung up here.

**Comment by dallinb** [comment]
The module has been tested against CentOS 6 but if something weird is happening with the generation of the YAML, it's likely to be the Ruby version.

**Comment by tibers** [comment]
OK I am pretty sure there's a legit issue here. 
```
[root@somehostname cassandra]# uname -a
Linux somehostname 2.6.32-642.1.1.el6.x86_64 #1 SMP Fri May 6 14:54:05 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@somehostname cassandra]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.8 (Santiago)
```

On the puppet server:
```
[root@puppet bofh]# ruby --version
ruby 2.0.0p598 (2014-11-13) [x86_64-linux]
```

Hiera...
```
# https://forge.puppetlabs.com/locp/cassandra
# This are not a comprehensive list of options, just what we'd use
# THIS IS THE NEW API FORMAT FOR VERSION 2+ OF THE MODULE
cassandra::settings:
  authenticator: AllowAllAuthenticator
  authorizer: AllowAllAuthorizer
  auto_bootstrap: true
  auto_snapshot: true
  batchlog_replay_throttle_in_kb: 0
  batch_size_warn_threshold_in_kb: 5
  # Leave the following two blank to automatically use the eth* address on the externally facing NIC determined by magic
  broadcast_address:
  broadcast_rpc_address:
  cas_contention_timeout_in_ms: 1000
  # https://issues.apache.org/jira/browse/CASSANDRA-9822
  cassandra_9822: false
  cluster_name: Default Unnamed Cluster
  column_index_size_in_kb: 64
  commit_failure_policy: stop
  commitlog_directory: /var/lib/cassandra/commitlog
  compaction_throughput_mb_per_sec: 0
  # The following four settings are the suggested values for SSD enabled hosts or virt + fast storage
  concurrent_writes: 128
  concurrent_counter_writes: 64
  concurrent_reads: 128
  concurrent_compactors: 8
  data_file_directories:
    - /var/lib/cassandra/commitlog/data-1
    - /var/lib/cassandra/commitlog/data-2
  disk_failure_policy: stop
  endpoint_snitch: GossipingPropertyFileSnitch
  hints_directory: /var/lib/cassandra/hints
  incremental_backups: true
  # This is counter-intuitive - just leave it blank for "auto"
  key_cache_size_in_mb:
  # Should only be specified in environments with multiple rings on the same physical node?
  listen_address: "%{::ipaddress}"
  # This doesn't work in cassandra 2.0
  listen_interface: eth0
  #cassandra::memory_allocator: NativeAllocator
  manage_dsc_repo: true
  memtable_flush_writers: 8
  rpc_address: "%{::ipaddress}"
  saved_caches_directory: /var/lib/cassandra/saved_caches
  seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
        - seeds: "%{::fqdn}"
  service_enable: true
  # This should be handled on a per cluster basis
  service_refresh: false
  #service_systemd: false
  # Make users unhappy
  tombstone_failure_threshold: 250000
  tombstone_warn_threshold: 100000
  trickle_fsync: true

cassandra::dc: mydatacenter
cassandra::rack: RAC1
cassandra::package_ensure: 3.0.5-1
cassandra::package_name: cassandra30
cassandra::datastax_agent::package_name: dsc30
cassandra::datastax_agent::package_ensure:  3.0.5-1
```

The yaml file this generates is:
```
# This file is managed by Puppet.  Manual changes are likely to be
# overwritten.  If you see that the YAML indentation looks somewhat strange,
# don't worry, please see the following ticker for more details.
# https://tickets.puppetlabs.com/browse/PUP-3120
---
dc: mydatacenter
cluster_name: Default Unnamed Cluster
seeds: somehost
```
